version: '3'

services:
  backend:
    build: backend/
    ports:
      - 5038:5038
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: frontend/
    ports:
      - 3000:80
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
